# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '8.0'

target 'OpenMed' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpenMed
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'GoogleMaps'
  pod 'Firebase/Messaging'
  pod 'Stripe'

end
